# Generated by Django 3.2.19 on 2023-06-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard_api', '0002_rename_leaderboard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
